name: Build and run agent

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-run-agent:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: |
        cd rtun
        echo ${{ secrets.MY_CONN_URL_DEV }}
        cargo run --release --bin rtun -- agent pub "${{ secrets.MY_CONN_URL_DEV }}" --agent rtun --expire_in 240

