name: Build docker

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build-and-push-rtun-image:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        cd rtun
        cargo build --release
        cp ./target/release/rtun ../docker/build/
        cd ../docker/build 
        docker build -t ubuntu-rtun .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag ubuntu-rtun simonfucn/ubuntu-rtun
        docker push simonfucn/ubuntu-rtun

