name: Run docker

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  REPO_GIT_HASH: ${{ github.sha }}

jobs:
  run-agent:

    runs-on: ubuntu-latest
    container: simonfucn/ubuntu-rtun:latest

    steps:

    - name: run-agent
      run: |
        rtun agent pub "${{ secrets.MY_CONN_URL }}" --agent rtun --expire_in 60 --secret ${{ secrets.MY_CONN_SECRET }}


