name: Schedule build-rtun-2

on:
    schedule:
        - cron:  '0 0,2,4,6,8,10,12,14,16,18,20,22 * * *'

env:
  CARGO_TERM_COLOR: always
  REPO_GIT_HASH: ${{ github.sha }}

jobs:
  build-rtun-2:

    runs-on: ubuntu-latest
    container: simonfucn/ubuntu-rtun:latest

    steps:

    - name: run-agent
      run: |
        rtun agent pub "${{ secrets.MY_CONN_URL }}" --agent rtun-2 --expire_in 110


