name: Schedule build-rtun-1

on:
    schedule:
        - cron:  '0 1,3,5,7,9,11,13,15,17,19,21,23 * * *'

env:
  CARGO_TERM_COLOR: always
  REPO_GIT_HASH: ${{ github.sha }}

jobs:
  build-rtun-1:

    runs-on: ubuntu-latest
    container: simonfucn/ubuntu-rtun:latest

    steps:

    - name: run-agent
      run: |
        rtun agent pub "${{ secrets.MY_CONN_URL }}" --agent rtun-1 --expire_in 110


